name: CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - name: 'Checkout sources'
      uses: actions/checkout@v2
    - name: 'Setup NodeJS'
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - run: yarn install
    - run: yarn test
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release
      if: github.ref == 'refs/heads/master' && job.status == 'success'
