name: CICD

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn install
    - run: yarn test
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release
      if: github.ref == 'refs/heads/master' && job.status == 'success'
